# Generated by Django 6.0 on 2025-12-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
